server:
  port: 9000
spring:
  mail:
    host: smtp.google.com

  servlet:
    multipart:
      max-file-size: 2MB

tensor:
  labelPath: mscoco_label_map.pbtxt
  modelPath: frozen_inference_graph.pb
  confidenceLimit: 0.2
  maxPoolSize: 5
