// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/pipeline.proto

package object_detection.protos;

public final class Pipeline {
  private Pipeline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrainEvalPipelineConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:object_detection.protos.TrainEvalPipelineConfig)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<TrainEvalPipelineConfig> {

    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    boolean hasModel();
    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    object_detection.protos.Model.DetectionModel getModel();
    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    object_detection.protos.Model.DetectionModelOrBuilder getModelOrBuilder();

    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    boolean hasTrainConfig();
    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    object_detection.protos.Train.TrainConfig getTrainConfig();
    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    object_detection.protos.Train.TrainConfigOrBuilder getTrainConfigOrBuilder();

    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    boolean hasTrainInputReader();
    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    object_detection.protos.InputReaderOuterClass.InputReader getTrainInputReader();
    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getTrainInputReaderOrBuilder();

    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    boolean hasEvalConfig();
    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    object_detection.protos.Eval.EvalConfig getEvalConfig();
    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    object_detection.protos.Eval.EvalConfigOrBuilder getEvalConfigOrBuilder();

    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    boolean hasEvalInputReader();
    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    object_detection.protos.InputReaderOuterClass.InputReader getEvalInputReader();
    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getEvalInputReaderOrBuilder();

    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    boolean hasGraphRewriter();
    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    object_detection.protos.GraphRewriterOuterClass.GraphRewriter getGraphRewriter();
    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder getGraphRewriterOrBuilder();
  }
  /**
   * <pre>
   * Convenience message for configuring a training and eval pipeline. Allows all
   * of the pipeline parameters to be configured from one file.
   * </pre>
   *
   * Protobuf type {@code object_detection.protos.TrainEvalPipelineConfig}
   */
  public  static final class TrainEvalPipelineConfig extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        TrainEvalPipelineConfig> implements
      // @@protoc_insertion_point(message_implements:object_detection.protos.TrainEvalPipelineConfig)
      TrainEvalPipelineConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrainEvalPipelineConfig.newBuilder() to construct.
    private TrainEvalPipelineConfig(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<object_detection.protos.Pipeline.TrainEvalPipelineConfig, ?> builder) {
      super(builder);
    }
    private TrainEvalPipelineConfig() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrainEvalPipelineConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              object_detection.protos.Model.DetectionModel.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = model_.toBuilder();
              }
              model_ = input.readMessage(object_detection.protos.Model.DetectionModel.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(model_);
                model_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              object_detection.protos.Train.TrainConfig.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = trainConfig_.toBuilder();
              }
              trainConfig_ = input.readMessage(object_detection.protos.Train.TrainConfig.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trainConfig_);
                trainConfig_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              object_detection.protos.InputReaderOuterClass.InputReader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = trainInputReader_.toBuilder();
              }
              trainInputReader_ = input.readMessage(object_detection.protos.InputReaderOuterClass.InputReader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trainInputReader_);
                trainInputReader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              object_detection.protos.Eval.EvalConfig.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = evalConfig_.toBuilder();
              }
              evalConfig_ = input.readMessage(object_detection.protos.Eval.EvalConfig.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(evalConfig_);
                evalConfig_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              object_detection.protos.InputReaderOuterClass.InputReader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = evalInputReader_.toBuilder();
              }
              evalInputReader_ = input.readMessage(object_detection.protos.InputReaderOuterClass.InputReader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(evalInputReader_);
                evalInputReader_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = graphRewriter_.toBuilder();
              }
              graphRewriter_ = input.readMessage(object_detection.protos.GraphRewriterOuterClass.GraphRewriter.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(graphRewriter_);
                graphRewriter_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return object_detection.protos.Pipeline.internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return object_detection.protos.Pipeline.internal_static_object_detection_protos_TrainEvalPipelineConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              object_detection.protos.Pipeline.TrainEvalPipelineConfig.class, object_detection.protos.Pipeline.TrainEvalPipelineConfig.Builder.class);
    }

    private int bitField0_;
    public static final int MODEL_FIELD_NUMBER = 1;
    private object_detection.protos.Model.DetectionModel model_;
    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    public object_detection.protos.Model.DetectionModel getModel() {
      return model_ == null ? object_detection.protos.Model.DetectionModel.getDefaultInstance() : model_;
    }
    /**
     * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
     */
    public object_detection.protos.Model.DetectionModelOrBuilder getModelOrBuilder() {
      return model_ == null ? object_detection.protos.Model.DetectionModel.getDefaultInstance() : model_;
    }

    public static final int TRAIN_CONFIG_FIELD_NUMBER = 2;
    private object_detection.protos.Train.TrainConfig trainConfig_;
    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    public boolean hasTrainConfig() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    public object_detection.protos.Train.TrainConfig getTrainConfig() {
      return trainConfig_ == null ? object_detection.protos.Train.TrainConfig.getDefaultInstance() : trainConfig_;
    }
    /**
     * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
     */
    public object_detection.protos.Train.TrainConfigOrBuilder getTrainConfigOrBuilder() {
      return trainConfig_ == null ? object_detection.protos.Train.TrainConfig.getDefaultInstance() : trainConfig_;
    }

    public static final int TRAIN_INPUT_READER_FIELD_NUMBER = 3;
    private object_detection.protos.InputReaderOuterClass.InputReader trainInputReader_;
    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    public boolean hasTrainInputReader() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    public object_detection.protos.InputReaderOuterClass.InputReader getTrainInputReader() {
      return trainInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : trainInputReader_;
    }
    /**
     * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
     */
    public object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getTrainInputReaderOrBuilder() {
      return trainInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : trainInputReader_;
    }

    public static final int EVAL_CONFIG_FIELD_NUMBER = 4;
    private object_detection.protos.Eval.EvalConfig evalConfig_;
    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    public boolean hasEvalConfig() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    public object_detection.protos.Eval.EvalConfig getEvalConfig() {
      return evalConfig_ == null ? object_detection.protos.Eval.EvalConfig.getDefaultInstance() : evalConfig_;
    }
    /**
     * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
     */
    public object_detection.protos.Eval.EvalConfigOrBuilder getEvalConfigOrBuilder() {
      return evalConfig_ == null ? object_detection.protos.Eval.EvalConfig.getDefaultInstance() : evalConfig_;
    }

    public static final int EVAL_INPUT_READER_FIELD_NUMBER = 5;
    private object_detection.protos.InputReaderOuterClass.InputReader evalInputReader_;
    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    public boolean hasEvalInputReader() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    public object_detection.protos.InputReaderOuterClass.InputReader getEvalInputReader() {
      return evalInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : evalInputReader_;
    }
    /**
     * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
     */
    public object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getEvalInputReaderOrBuilder() {
      return evalInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : evalInputReader_;
    }

    public static final int GRAPH_REWRITER_FIELD_NUMBER = 6;
    private object_detection.protos.GraphRewriterOuterClass.GraphRewriter graphRewriter_;
    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    public boolean hasGraphRewriter() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    public object_detection.protos.GraphRewriterOuterClass.GraphRewriter getGraphRewriter() {
      return graphRewriter_ == null ? object_detection.protos.GraphRewriterOuterClass.GraphRewriter.getDefaultInstance() : graphRewriter_;
    }
    /**
     * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
     */
    public object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder getGraphRewriterOrBuilder() {
      return graphRewriter_ == null ? object_detection.protos.GraphRewriterOuterClass.GraphRewriter.getDefaultInstance() : graphRewriter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasTrainInputReader()) {
        if (!getTrainInputReader().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasEvalInputReader()) {
        if (!getEvalInputReader().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<object_detection.protos.Pipeline.TrainEvalPipelineConfig>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getModel());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getTrainConfig());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getTrainInputReader());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getEvalConfig());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getEvalInputReader());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, getGraphRewriter());
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModel());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTrainConfig());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTrainInputReader());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEvalConfig());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getEvalInputReader());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getGraphRewriter());
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof object_detection.protos.Pipeline.TrainEvalPipelineConfig)) {
        return super.equals(obj);
      }
      object_detection.protos.Pipeline.TrainEvalPipelineConfig other = (object_detection.protos.Pipeline.TrainEvalPipelineConfig) obj;

      boolean result = true;
      result = result && (hasModel() == other.hasModel());
      if (hasModel()) {
        result = result && getModel()
            .equals(other.getModel());
      }
      result = result && (hasTrainConfig() == other.hasTrainConfig());
      if (hasTrainConfig()) {
        result = result && getTrainConfig()
            .equals(other.getTrainConfig());
      }
      result = result && (hasTrainInputReader() == other.hasTrainInputReader());
      if (hasTrainInputReader()) {
        result = result && getTrainInputReader()
            .equals(other.getTrainInputReader());
      }
      result = result && (hasEvalConfig() == other.hasEvalConfig());
      if (hasEvalConfig()) {
        result = result && getEvalConfig()
            .equals(other.getEvalConfig());
      }
      result = result && (hasEvalInputReader() == other.hasEvalInputReader());
      if (hasEvalInputReader()) {
        result = result && getEvalInputReader()
            .equals(other.getEvalInputReader());
      }
      result = result && (hasGraphRewriter() == other.hasGraphRewriter());
      if (hasGraphRewriter()) {
        result = result && getGraphRewriter()
            .equals(other.getGraphRewriter());
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModel()) {
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel().hashCode();
      }
      if (hasTrainConfig()) {
        hash = (37 * hash) + TRAIN_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getTrainConfig().hashCode();
      }
      if (hasTrainInputReader()) {
        hash = (37 * hash) + TRAIN_INPUT_READER_FIELD_NUMBER;
        hash = (53 * hash) + getTrainInputReader().hashCode();
      }
      if (hasEvalConfig()) {
        hash = (37 * hash) + EVAL_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getEvalConfig().hashCode();
      }
      if (hasEvalInputReader()) {
        hash = (37 * hash) + EVAL_INPUT_READER_FIELD_NUMBER;
        hash = (53 * hash) + getEvalInputReader().hashCode();
      }
      if (hasGraphRewriter()) {
        hash = (37 * hash) + GRAPH_REWRITER_FIELD_NUMBER;
        hash = (53 * hash) + getGraphRewriter().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(object_detection.protos.Pipeline.TrainEvalPipelineConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Convenience message for configuring a training and eval pipeline. Allows all
     * of the pipeline parameters to be configured from one file.
     * </pre>
     *
     * Protobuf type {@code object_detection.protos.TrainEvalPipelineConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          object_detection.protos.Pipeline.TrainEvalPipelineConfig, Builder> implements
        // @@protoc_insertion_point(builder_implements:object_detection.protos.TrainEvalPipelineConfig)
        object_detection.protos.Pipeline.TrainEvalPipelineConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return object_detection.protos.Pipeline.internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return object_detection.protos.Pipeline.internal_static_object_detection_protos_TrainEvalPipelineConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                object_detection.protos.Pipeline.TrainEvalPipelineConfig.class, object_detection.protos.Pipeline.TrainEvalPipelineConfig.Builder.class);
      }

      // Construct using object_detection.protos.Pipeline.TrainEvalPipelineConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getModelFieldBuilder();
          getTrainConfigFieldBuilder();
          getTrainInputReaderFieldBuilder();
          getEvalConfigFieldBuilder();
          getEvalInputReaderFieldBuilder();
          getGraphRewriterFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (modelBuilder_ == null) {
          model_ = null;
        } else {
          modelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (trainConfigBuilder_ == null) {
          trainConfig_ = null;
        } else {
          trainConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (trainInputReaderBuilder_ == null) {
          trainInputReader_ = null;
        } else {
          trainInputReaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (evalConfigBuilder_ == null) {
          evalConfig_ = null;
        } else {
          evalConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (evalInputReaderBuilder_ == null) {
          evalInputReader_ = null;
        } else {
          evalInputReaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (graphRewriterBuilder_ == null) {
          graphRewriter_ = null;
        } else {
          graphRewriterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return object_detection.protos.Pipeline.internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor;
      }

      @java.lang.Override
      public object_detection.protos.Pipeline.TrainEvalPipelineConfig getDefaultInstanceForType() {
        return object_detection.protos.Pipeline.TrainEvalPipelineConfig.getDefaultInstance();
      }

      @java.lang.Override
      public object_detection.protos.Pipeline.TrainEvalPipelineConfig build() {
        object_detection.protos.Pipeline.TrainEvalPipelineConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public object_detection.protos.Pipeline.TrainEvalPipelineConfig buildPartial() {
        object_detection.protos.Pipeline.TrainEvalPipelineConfig result = new object_detection.protos.Pipeline.TrainEvalPipelineConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (modelBuilder_ == null) {
          result.model_ = model_;
        } else {
          result.model_ = modelBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (trainConfigBuilder_ == null) {
          result.trainConfig_ = trainConfig_;
        } else {
          result.trainConfig_ = trainConfigBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (trainInputReaderBuilder_ == null) {
          result.trainInputReader_ = trainInputReader_;
        } else {
          result.trainInputReader_ = trainInputReaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (evalConfigBuilder_ == null) {
          result.evalConfig_ = evalConfig_;
        } else {
          result.evalConfig_ = evalConfigBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (evalInputReaderBuilder_ == null) {
          result.evalInputReader_ = evalInputReader_;
        } else {
          result.evalInputReader_ = evalInputReaderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (graphRewriterBuilder_ == null) {
          result.graphRewriter_ = graphRewriter_;
        } else {
          result.graphRewriter_ = graphRewriterBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              object_detection.protos.Pipeline.TrainEvalPipelineConfig, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              object_detection.protos.Pipeline.TrainEvalPipelineConfig, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      @java.lang.Override
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              object_detection.protos.Pipeline.TrainEvalPipelineConfig, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              object_detection.protos.Pipeline.TrainEvalPipelineConfig, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof object_detection.protos.Pipeline.TrainEvalPipelineConfig) {
          return mergeFrom((object_detection.protos.Pipeline.TrainEvalPipelineConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(object_detection.protos.Pipeline.TrainEvalPipelineConfig other) {
        if (other == object_detection.protos.Pipeline.TrainEvalPipelineConfig.getDefaultInstance()) return this;
        if (other.hasModel()) {
          mergeModel(other.getModel());
        }
        if (other.hasTrainConfig()) {
          mergeTrainConfig(other.getTrainConfig());
        }
        if (other.hasTrainInputReader()) {
          mergeTrainInputReader(other.getTrainInputReader());
        }
        if (other.hasEvalConfig()) {
          mergeEvalConfig(other.getEvalConfig());
        }
        if (other.hasEvalInputReader()) {
          mergeEvalInputReader(other.getEvalInputReader());
        }
        if (other.hasGraphRewriter()) {
          mergeGraphRewriter(other.getGraphRewriter());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasTrainInputReader()) {
          if (!getTrainInputReader().isInitialized()) {
            return false;
          }
        }
        if (hasEvalInputReader()) {
          if (!getEvalInputReader().isInitialized()) {
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        object_detection.protos.Pipeline.TrainEvalPipelineConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (object_detection.protos.Pipeline.TrainEvalPipelineConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private object_detection.protos.Model.DetectionModel model_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Model.DetectionModel, object_detection.protos.Model.DetectionModel.Builder, object_detection.protos.Model.DetectionModelOrBuilder> modelBuilder_;
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public object_detection.protos.Model.DetectionModel getModel() {
        if (modelBuilder_ == null) {
          return model_ == null ? object_detection.protos.Model.DetectionModel.getDefaultInstance() : model_;
        } else {
          return modelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public Builder setModel(object_detection.protos.Model.DetectionModel value) {
        if (modelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          model_ = value;
          onChanged();
        } else {
          modelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public Builder setModel(
          object_detection.protos.Model.DetectionModel.Builder builderForValue) {
        if (modelBuilder_ == null) {
          model_ = builderForValue.build();
          onChanged();
        } else {
          modelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public Builder mergeModel(object_detection.protos.Model.DetectionModel value) {
        if (modelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              model_ != null &&
              model_ != object_detection.protos.Model.DetectionModel.getDefaultInstance()) {
            model_ =
              object_detection.protos.Model.DetectionModel.newBuilder(model_).mergeFrom(value).buildPartial();
          } else {
            model_ = value;
          }
          onChanged();
        } else {
          modelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public Builder clearModel() {
        if (modelBuilder_ == null) {
          model_ = null;
          onChanged();
        } else {
          modelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public object_detection.protos.Model.DetectionModel.Builder getModelBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getModelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      public object_detection.protos.Model.DetectionModelOrBuilder getModelOrBuilder() {
        if (modelBuilder_ != null) {
          return modelBuilder_.getMessageOrBuilder();
        } else {
          return model_ == null ?
              object_detection.protos.Model.DetectionModel.getDefaultInstance() : model_;
        }
      }
      /**
       * <code>optional .object_detection.protos.DetectionModel model = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Model.DetectionModel, object_detection.protos.Model.DetectionModel.Builder, object_detection.protos.Model.DetectionModelOrBuilder> 
          getModelFieldBuilder() {
        if (modelBuilder_ == null) {
          modelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.Model.DetectionModel, object_detection.protos.Model.DetectionModel.Builder, object_detection.protos.Model.DetectionModelOrBuilder>(
                  getModel(),
                  getParentForChildren(),
                  isClean());
          model_ = null;
        }
        return modelBuilder_;
      }

      private object_detection.protos.Train.TrainConfig trainConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Train.TrainConfig, object_detection.protos.Train.TrainConfig.Builder, object_detection.protos.Train.TrainConfigOrBuilder> trainConfigBuilder_;
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public boolean hasTrainConfig() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public object_detection.protos.Train.TrainConfig getTrainConfig() {
        if (trainConfigBuilder_ == null) {
          return trainConfig_ == null ? object_detection.protos.Train.TrainConfig.getDefaultInstance() : trainConfig_;
        } else {
          return trainConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public Builder setTrainConfig(object_detection.protos.Train.TrainConfig value) {
        if (trainConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trainConfig_ = value;
          onChanged();
        } else {
          trainConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public Builder setTrainConfig(
          object_detection.protos.Train.TrainConfig.Builder builderForValue) {
        if (trainConfigBuilder_ == null) {
          trainConfig_ = builderForValue.build();
          onChanged();
        } else {
          trainConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public Builder mergeTrainConfig(object_detection.protos.Train.TrainConfig value) {
        if (trainConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              trainConfig_ != null &&
              trainConfig_ != object_detection.protos.Train.TrainConfig.getDefaultInstance()) {
            trainConfig_ =
              object_detection.protos.Train.TrainConfig.newBuilder(trainConfig_).mergeFrom(value).buildPartial();
          } else {
            trainConfig_ = value;
          }
          onChanged();
        } else {
          trainConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public Builder clearTrainConfig() {
        if (trainConfigBuilder_ == null) {
          trainConfig_ = null;
          onChanged();
        } else {
          trainConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public object_detection.protos.Train.TrainConfig.Builder getTrainConfigBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTrainConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      public object_detection.protos.Train.TrainConfigOrBuilder getTrainConfigOrBuilder() {
        if (trainConfigBuilder_ != null) {
          return trainConfigBuilder_.getMessageOrBuilder();
        } else {
          return trainConfig_ == null ?
              object_detection.protos.Train.TrainConfig.getDefaultInstance() : trainConfig_;
        }
      }
      /**
       * <code>optional .object_detection.protos.TrainConfig train_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Train.TrainConfig, object_detection.protos.Train.TrainConfig.Builder, object_detection.protos.Train.TrainConfigOrBuilder> 
          getTrainConfigFieldBuilder() {
        if (trainConfigBuilder_ == null) {
          trainConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.Train.TrainConfig, object_detection.protos.Train.TrainConfig.Builder, object_detection.protos.Train.TrainConfigOrBuilder>(
                  getTrainConfig(),
                  getParentForChildren(),
                  isClean());
          trainConfig_ = null;
        }
        return trainConfigBuilder_;
      }

      private object_detection.protos.InputReaderOuterClass.InputReader trainInputReader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder> trainInputReaderBuilder_;
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public boolean hasTrainInputReader() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReader getTrainInputReader() {
        if (trainInputReaderBuilder_ == null) {
          return trainInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : trainInputReader_;
        } else {
          return trainInputReaderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public Builder setTrainInputReader(object_detection.protos.InputReaderOuterClass.InputReader value) {
        if (trainInputReaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trainInputReader_ = value;
          onChanged();
        } else {
          trainInputReaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public Builder setTrainInputReader(
          object_detection.protos.InputReaderOuterClass.InputReader.Builder builderForValue) {
        if (trainInputReaderBuilder_ == null) {
          trainInputReader_ = builderForValue.build();
          onChanged();
        } else {
          trainInputReaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public Builder mergeTrainInputReader(object_detection.protos.InputReaderOuterClass.InputReader value) {
        if (trainInputReaderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              trainInputReader_ != null &&
              trainInputReader_ != object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance()) {
            trainInputReader_ =
              object_detection.protos.InputReaderOuterClass.InputReader.newBuilder(trainInputReader_).mergeFrom(value).buildPartial();
          } else {
            trainInputReader_ = value;
          }
          onChanged();
        } else {
          trainInputReaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public Builder clearTrainInputReader() {
        if (trainInputReaderBuilder_ == null) {
          trainInputReader_ = null;
          onChanged();
        } else {
          trainInputReaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReader.Builder getTrainInputReaderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTrainInputReaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getTrainInputReaderOrBuilder() {
        if (trainInputReaderBuilder_ != null) {
          return trainInputReaderBuilder_.getMessageOrBuilder();
        } else {
          return trainInputReader_ == null ?
              object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : trainInputReader_;
        }
      }
      /**
       * <code>optional .object_detection.protos.InputReader train_input_reader = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder> 
          getTrainInputReaderFieldBuilder() {
        if (trainInputReaderBuilder_ == null) {
          trainInputReaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder>(
                  getTrainInputReader(),
                  getParentForChildren(),
                  isClean());
          trainInputReader_ = null;
        }
        return trainInputReaderBuilder_;
      }

      private object_detection.protos.Eval.EvalConfig evalConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Eval.EvalConfig, object_detection.protos.Eval.EvalConfig.Builder, object_detection.protos.Eval.EvalConfigOrBuilder> evalConfigBuilder_;
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public boolean hasEvalConfig() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public object_detection.protos.Eval.EvalConfig getEvalConfig() {
        if (evalConfigBuilder_ == null) {
          return evalConfig_ == null ? object_detection.protos.Eval.EvalConfig.getDefaultInstance() : evalConfig_;
        } else {
          return evalConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public Builder setEvalConfig(object_detection.protos.Eval.EvalConfig value) {
        if (evalConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evalConfig_ = value;
          onChanged();
        } else {
          evalConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public Builder setEvalConfig(
          object_detection.protos.Eval.EvalConfig.Builder builderForValue) {
        if (evalConfigBuilder_ == null) {
          evalConfig_ = builderForValue.build();
          onChanged();
        } else {
          evalConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public Builder mergeEvalConfig(object_detection.protos.Eval.EvalConfig value) {
        if (evalConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              evalConfig_ != null &&
              evalConfig_ != object_detection.protos.Eval.EvalConfig.getDefaultInstance()) {
            evalConfig_ =
              object_detection.protos.Eval.EvalConfig.newBuilder(evalConfig_).mergeFrom(value).buildPartial();
          } else {
            evalConfig_ = value;
          }
          onChanged();
        } else {
          evalConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public Builder clearEvalConfig() {
        if (evalConfigBuilder_ == null) {
          evalConfig_ = null;
          onChanged();
        } else {
          evalConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public object_detection.protos.Eval.EvalConfig.Builder getEvalConfigBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getEvalConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      public object_detection.protos.Eval.EvalConfigOrBuilder getEvalConfigOrBuilder() {
        if (evalConfigBuilder_ != null) {
          return evalConfigBuilder_.getMessageOrBuilder();
        } else {
          return evalConfig_ == null ?
              object_detection.protos.Eval.EvalConfig.getDefaultInstance() : evalConfig_;
        }
      }
      /**
       * <code>optional .object_detection.protos.EvalConfig eval_config = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.Eval.EvalConfig, object_detection.protos.Eval.EvalConfig.Builder, object_detection.protos.Eval.EvalConfigOrBuilder> 
          getEvalConfigFieldBuilder() {
        if (evalConfigBuilder_ == null) {
          evalConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.Eval.EvalConfig, object_detection.protos.Eval.EvalConfig.Builder, object_detection.protos.Eval.EvalConfigOrBuilder>(
                  getEvalConfig(),
                  getParentForChildren(),
                  isClean());
          evalConfig_ = null;
        }
        return evalConfigBuilder_;
      }

      private object_detection.protos.InputReaderOuterClass.InputReader evalInputReader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder> evalInputReaderBuilder_;
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public boolean hasEvalInputReader() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReader getEvalInputReader() {
        if (evalInputReaderBuilder_ == null) {
          return evalInputReader_ == null ? object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : evalInputReader_;
        } else {
          return evalInputReaderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public Builder setEvalInputReader(object_detection.protos.InputReaderOuterClass.InputReader value) {
        if (evalInputReaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evalInputReader_ = value;
          onChanged();
        } else {
          evalInputReaderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public Builder setEvalInputReader(
          object_detection.protos.InputReaderOuterClass.InputReader.Builder builderForValue) {
        if (evalInputReaderBuilder_ == null) {
          evalInputReader_ = builderForValue.build();
          onChanged();
        } else {
          evalInputReaderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public Builder mergeEvalInputReader(object_detection.protos.InputReaderOuterClass.InputReader value) {
        if (evalInputReaderBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              evalInputReader_ != null &&
              evalInputReader_ != object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance()) {
            evalInputReader_ =
              object_detection.protos.InputReaderOuterClass.InputReader.newBuilder(evalInputReader_).mergeFrom(value).buildPartial();
          } else {
            evalInputReader_ = value;
          }
          onChanged();
        } else {
          evalInputReaderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public Builder clearEvalInputReader() {
        if (evalInputReaderBuilder_ == null) {
          evalInputReader_ = null;
          onChanged();
        } else {
          evalInputReaderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReader.Builder getEvalInputReaderBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getEvalInputReaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      public object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder getEvalInputReaderOrBuilder() {
        if (evalInputReaderBuilder_ != null) {
          return evalInputReaderBuilder_.getMessageOrBuilder();
        } else {
          return evalInputReader_ == null ?
              object_detection.protos.InputReaderOuterClass.InputReader.getDefaultInstance() : evalInputReader_;
        }
      }
      /**
       * <code>optional .object_detection.protos.InputReader eval_input_reader = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder> 
          getEvalInputReaderFieldBuilder() {
        if (evalInputReaderBuilder_ == null) {
          evalInputReaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.InputReaderOuterClass.InputReader, object_detection.protos.InputReaderOuterClass.InputReader.Builder, object_detection.protos.InputReaderOuterClass.InputReaderOrBuilder>(
                  getEvalInputReader(),
                  getParentForChildren(),
                  isClean());
          evalInputReader_ = null;
        }
        return evalInputReaderBuilder_;
      }

      private object_detection.protos.GraphRewriterOuterClass.GraphRewriter graphRewriter_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.GraphRewriterOuterClass.GraphRewriter, object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder, object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder> graphRewriterBuilder_;
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public boolean hasGraphRewriter() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public object_detection.protos.GraphRewriterOuterClass.GraphRewriter getGraphRewriter() {
        if (graphRewriterBuilder_ == null) {
          return graphRewriter_ == null ? object_detection.protos.GraphRewriterOuterClass.GraphRewriter.getDefaultInstance() : graphRewriter_;
        } else {
          return graphRewriterBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public Builder setGraphRewriter(object_detection.protos.GraphRewriterOuterClass.GraphRewriter value) {
        if (graphRewriterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          graphRewriter_ = value;
          onChanged();
        } else {
          graphRewriterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public Builder setGraphRewriter(
          object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder builderForValue) {
        if (graphRewriterBuilder_ == null) {
          graphRewriter_ = builderForValue.build();
          onChanged();
        } else {
          graphRewriterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public Builder mergeGraphRewriter(object_detection.protos.GraphRewriterOuterClass.GraphRewriter value) {
        if (graphRewriterBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              graphRewriter_ != null &&
              graphRewriter_ != object_detection.protos.GraphRewriterOuterClass.GraphRewriter.getDefaultInstance()) {
            graphRewriter_ =
              object_detection.protos.GraphRewriterOuterClass.GraphRewriter.newBuilder(graphRewriter_).mergeFrom(value).buildPartial();
          } else {
            graphRewriter_ = value;
          }
          onChanged();
        } else {
          graphRewriterBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public Builder clearGraphRewriter() {
        if (graphRewriterBuilder_ == null) {
          graphRewriter_ = null;
          onChanged();
        } else {
          graphRewriterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder getGraphRewriterBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getGraphRewriterFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      public object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder getGraphRewriterOrBuilder() {
        if (graphRewriterBuilder_ != null) {
          return graphRewriterBuilder_.getMessageOrBuilder();
        } else {
          return graphRewriter_ == null ?
              object_detection.protos.GraphRewriterOuterClass.GraphRewriter.getDefaultInstance() : graphRewriter_;
        }
      }
      /**
       * <code>optional .object_detection.protos.GraphRewriter graph_rewriter = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          object_detection.protos.GraphRewriterOuterClass.GraphRewriter, object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder, object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder> 
          getGraphRewriterFieldBuilder() {
        if (graphRewriterBuilder_ == null) {
          graphRewriterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              object_detection.protos.GraphRewriterOuterClass.GraphRewriter, object_detection.protos.GraphRewriterOuterClass.GraphRewriter.Builder, object_detection.protos.GraphRewriterOuterClass.GraphRewriterOrBuilder>(
                  getGraphRewriter(),
                  getParentForChildren(),
                  isClean());
          graphRewriter_ = null;
        }
        return graphRewriterBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:object_detection.protos.TrainEvalPipelineConfig)
    }

    // @@protoc_insertion_point(class_scope:object_detection.protos.TrainEvalPipelineConfig)
    private static final object_detection.protos.Pipeline.TrainEvalPipelineConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new object_detection.protos.Pipeline.TrainEvalPipelineConfig();
    }

    public static object_detection.protos.Pipeline.TrainEvalPipelineConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TrainEvalPipelineConfig>
        PARSER = new com.google.protobuf.AbstractParser<TrainEvalPipelineConfig>() {
      @java.lang.Override
      public TrainEvalPipelineConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrainEvalPipelineConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrainEvalPipelineConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainEvalPipelineConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public object_detection.protos.Pipeline.TrainEvalPipelineConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_object_detection_protos_TrainEvalPipelineConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&object_detection/protos/pipeline.proto" +
      "\022\027object_detection.protos\032\"object_detect" +
      "ion/protos/eval.proto\032,object_detection/" +
      "protos/graph_rewriter.proto\032*object_dete" +
      "ction/protos/input_reader.proto\032#object_" +
      "detection/protos/model.proto\032#object_det" +
      "ection/protos/train.proto\"\225\003\n\027TrainEvalP" +
      "ipelineConfig\0226\n\005model\030\001 \001(\0132\'.object_de" +
      "tection.protos.DetectionModel\022:\n\014train_c" +
      "onfig\030\002 \001(\0132$.object_detection.protos.Tr" +
      "ainConfig\022@\n\022train_input_reader\030\003 \001(\0132$." +
      "object_detection.protos.InputReader\0228\n\013e" +
      "val_config\030\004 \001(\0132#.object_detection.prot" +
      "os.EvalConfig\022?\n\021eval_input_reader\030\005 \001(\013" +
      "2$.object_detection.protos.InputReader\022>" +
      "\n\016graph_rewriter\030\006 \001(\0132&.object_detectio" +
      "n.protos.GraphRewriter*\t\010\350\007\020\200\200\200\200\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          object_detection.protos.Eval.getDescriptor(),
          object_detection.protos.GraphRewriterOuterClass.getDescriptor(),
          object_detection.protos.InputReaderOuterClass.getDescriptor(),
          object_detection.protos.Model.getDescriptor(),
          object_detection.protos.Train.getDescriptor(),
        }, assigner);
    internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_object_detection_protos_TrainEvalPipelineConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_object_detection_protos_TrainEvalPipelineConfig_descriptor,
        new java.lang.String[] { "Model", "TrainConfig", "TrainInputReader", "EvalConfig", "EvalInputReader", "GraphRewriter", });
    object_detection.protos.Eval.getDescriptor();
    object_detection.protos.GraphRewriterOuterClass.getDescriptor();
    object_detection.protos.InputReaderOuterClass.getDescriptor();
    object_detection.protos.Model.getDescriptor();
    object_detection.protos.Train.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
